### ISSUE TITLE
photos with '#' in the filename can not be displayed

### ISSUE THREAD

**Issue by mshoe007** [Svedrin/galry#5]
The thumbnail page shows the filename as a text hyperlink (http://127.0.0.1:8000/00#001.jpg) instead of the thumbnail. Clicking on the link results in a new page with this error

```
path '"/pictures/00"' does not exist
```

**Comment by Svedrin** [comment]
I was wondering why I hadn't just URLencoded the value as a whole, but when doing so, I quickly found out that this method would also encode the slashes used as path separators, thus breaking everything. [Tera has an exception for those](https://github.com/Keats/tera/blob/ae13d7ce39d732aae3f68435ed52c60732fe0ee0/src/builtins/filters/string.rs#L42-L43) in its `urlencode` filter though, so that one should work. Please give it a try. :slightly_smiling_face:

**Comment by mshoe007** [comment]
Yeah, I've been burned by URL encoding that also encodes the slashes.

Thanks - your change works.

Thanks for the super quick updates.
